###
GET http://localhost:3001/

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/179

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fred Simpson",
    "number": "123-456-7890"
}

###
PUT http://localhost:3001/api/persons/914
Content-Type: application/json

{
    "name": "Fred Simpson",
    "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "fred",
    "number": "123-456-7890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "12121212"
}